### ISSUE TITLE
@babel/preset-react

### ISSUE THREAD

**Issue by matthiask** [feinheit/fh-webpack-config#1]
Mir ist aufgefallen, dass die React Babel Config ohne preset-react auskommt -- ist das Absicht? Gibts einen Grund dafür?

**Comment by daenub** [comment]
Danke für den Hinweis. Ich habe die Config von einem Projekt kopiert. Darum war keine konkrete Überlegung dahinter, ausser dass bei der Verwendung in einem neuen React Projekt sicher noch eine Anpassung zur Konfiguration dazu kommt.
Ich habe es jetzt hinzugefügt --> https://github.com/feinheit/fh-webpack-config/commit/60d473810424b85529b13911edfb66cdeae0ae4a
